services:
  postgresdb:
    image: postgres:15
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root      
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - proxy

networks:
  proxy:
    external: true