services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "password"
    command: redis-server --requirepass password
    restart: always
    networks:
      - proxy
    volumes:
      - ./redis-data:/data  # Bind volume for Redis data persistence
    labels:
      - traefik.enable=true
      - traefik.http.routers.redis.rule=Host(`redis.dev.local`)
      - traefik.http.routers.redis.entrypoints=https
      - traefik.http.routers.redis.tls=true
      - traefik.http.services.redis.loadbalancer.server.port=6379

networks:
  proxy:
    external: true